# https://travis-ci.org/jwtk/jjwt

#sudo: required
language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk10

before_install:
  - if [ "${TRAVIS_JDK_VERSION}" == "oraclejdk7" ]; then export MAVEN_OPTS="-Dhttps.protocols=TLSv1.2 -Xmx512m -XX:MaxPermSize=128m"; fi
  # Set JAVA_HOME to where we want to install Oracle JDK 7:
  - if [ "${TRAVIS_JDK_VERSION}" == "oraclejdk7" ]; then export JAVA_HOME="/usr/lib/jvm/java-7-oracle"; export PATH="${JAVA_HOME}/bin:${PATH}"; fi
  # Download and install Oracle JDK 7:
  - if [ "${TRAVIS_JDK_VERSION}" == "oraclejdk7" ]; then test ! -d "${JAVA_HOME}" && (curl http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-7u80-linux-x64.tar.gz | sudo tar xz -C /usr/lib/jvm; sudo mv /usr/lib/jvm/jdk1.7.0_80 "${JAVA_HOME}"); fi
  # Download and install JCE Unlimited Strength Crypto policies for Oracle JDK 7:
  - if [ "${TRAVIS_JDK_VERSION}" == "oraclejdk7" ]; then curl -q -L -C - -b "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jce/7/UnlimitedJCEPolicyJDK7.zip -o /tmp/UnlimitedJCEPolicyJDK7.zip && sudo unzip -oj -d "$JAVA_HOME/jre/lib/security" /tmp/UnlimitedJCEPolicyJDK7.zip \*/\*.jar && rm /tmp/UnlimitedJCEPolicyJDK7.zip; fi
  # If on JDK 8, ensure build coverage assertions are run (we only need to run this on one JDK to reduce overall build times):
  - export BUILD_COVERAGE="$([ $TRAVIS_JDK_VERSION == 'oraclejdk8' ] && echo 'true')"

install: true

script: mvn install

after_success:
  - test -z "$BUILD_COVERAGE" || { mvn clean clover:setup test && mvn -pl . clover:clover clover:check coveralls:report; }
